// Code generated by Kitex v0.9.1. DO NOT EDIT.

package uploadfileservice

import (
	uploadfile "github.com/S240/AetherCloud/client/uploadfile/kitex_gen/uploadfile"
	server "github.com/cloudwego/kitex/server"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler uploadfile.UploadFileService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
