// Code generated by Kitex v0.9.1. DO NOT EDIT.
package uploadfileservice

import (
	uploadfile "github.com/S240/AetherCloud/client/uploadfile/kitex_gen/uploadfile"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler uploadfile.UploadFileService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler uploadfile.UploadFileService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
