// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	apigw "github.com/S240/AetherCloud/app/apigw/biz/router/apigw"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	apigw.Register(r)
}
