// Code generated by hertz generator.

package apigw

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _completeuploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuploadpresignurlsMw() []app.HandlerFunc {
	// your code...
	return nil
}
